In [1]:
print('Hello from Python - Deep into Neural Networks')

Hello from Python - Deep into Neural Networks


Tensor Basics

In [ ]:
import torch
import numpy as np

# tensor - default datatype is float32
# numpy - default datatype is float64

List

In [6]:
my_list1 = [1, 2, 3, 4, 5]
my_list2 = [[1, 2, 3, 4, 5],
            [11, 22, 33, 44, 55]
            ]

print(my_list1)
print(my_list2)

[1, 2, 3, 4, 5]
[[1, 2, 3, 4, 5], [11, 22, 33, 44, 55]]


Numpy Arrays

In [13]:
np1 = np.random.rand(5)
np2 = np.random.rand(3, 4)

print(np1)
print(np2)
print(np1.dtype, np2.dtype)

[0.15920047 0.12871123 0.29928919 0.17496501 0.87800078]
[[0.11461783 0.71935623 0.73290963 0.03135515]
 [0.91746163 0.88280642 0.98643101 0.74672491]
 [0.20001665 0.86595793 0.94102601 0.7867373 ]]
float64 float64


# #Tensors
Tensors are powerful than Numpy Arrays which are powerful than Python Lists

In [11]:
tensor_2d_1 = torch.randn(3)
tensor_2d_2 = torch.rand(3, 2)
tensor_2d_3 = torch.randn(3, 2)

print(tensor_2d_1)
print(tensor_2d_2)
print(tensor_2d_3)

tensor([1.0080, 0.3651, 0.0638])
tensor([[0.6676, 0.9053],
        [0.2004, 0.2019],
        [0.2598, 0.8550]])
tensor([[-1.4545,  0.8710],
        [-1.4729,  1.0837],
        [ 0.1087,  0.0435]])


3d tensors

In [15]:
tensor_3d_1 = torch.randn(2, 3, 4)
print(tensor_3d_1)
print(tensor_3d_1.dtype)

# 2 sets
# 3 rows and 4 columns

tensor([[[-1.1649, -0.2796, -1.6595, -1.1796],
         [-0.0214, -0.6051, -1.2362,  0.3210],
         [ 0.1078, -0.4008, -1.8707,  0.3403]],

        [[ 0.7632, -0.1155, -1.2555, -1.4107],
         [ 0.3409,  0.7744,  1.2131,  0.5383],
         [ 0.3284, -0.6797, -1.5956, -0.0392]]])
torch.float32


Create tensor out of numpy array

In [17]:
npTensor1 = torch.tensor(np1)
npTensor2 = torch.tensor(np2)
print(npTensor1)
print(npTensor2)

tensor([0.1592, 0.1287, 0.2993, 0.1750, 0.8780], dtype=torch.float64)
tensor([[0.1146, 0.7194, 0.7329, 0.0314],
        [0.9175, 0.8828, 0.9864, 0.7467],
        [0.2000, 0.8660, 0.9410, 0.7867]], dtype=torch.float64)
